### ISSUE TITLE
Doesn't work on Xcode 12.5, 14.5 IOS Devices

### ISSUE THREAD

**Issue by prncvrm** [yageek/iostrust#4]
Doesn't work on Xcode 12.5, IOS 14.5 devices, gives the following error.
```
error: No such file or directory @ rb_file_s_stat - /Users/<user>/Library/Developer/CoreSimulator/Devices/54D18DA4-9E42-41E2-BEF7-F0B6545A2EC5/data/Library/Keychains/TrustStore.sqlite3. Use --trace to view backtrace
```

**Comment by H2wk** [comment]
I have noticed the same.

**Comment by prncvrm** [comment]
@yageek can timeline you could share  for the fixes?

**Comment by yageek** [comment]
I'm in holiday for now 😛 I'll try to take a look when I returned home.

**Comment by prncvrm** [comment]
sure np, happy holidays 😃

**Comment by yageek** [comment]
I think you don't need this gem anymore. Using `simctl` `keychain` action, you have the option for free with Xcode:

 xcrun simctl keychain booted add-root-cert /path/to/certificate

Is this working for you?

**Comment by prncvrm** [comment]
sure @yageek , would give a try and let you know.

**Comment by prncvrm** [comment]
@yageek works pretty fine, 

closing the ticket. :-)
